### ISSUE TITLE
We have no bug in read.md

### ISSUE THREAD

**Issue by LazaroAlsina** [LazaroAlsina/GitHub_Activity#10]
Please add the text "bug" inside read.md

**Comment by z-shug** [comment]
Wait you want a bug? 
What type an ant or rollie pollie?

**Comment by LazaroAlsina** [comment]
@z-shug Please give me the rollie polie thingy. Anywhere in the read.md

**Comment by z-shug** [comment]
Ok I can go get that done now

**Comment by z-shug** [comment]
Just sent through the PR

**Comment by z-shug** [comment]
Bug added and approved
